//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCorp_Email_Pw
    {
        public int EmailID { get; set; }
        public string Email { get; set; }
        public bool CheckStatus { get; set; }
        public string CheckTable { get; set; }
        public byte CommandID { get; set; }
        public bool IsActive { get; set; }
        public int CreateBy { get; set; }
        public string CreateIP { get; set; }
        public DateTime CreateDate { get; set; }
        public int UpdateBy { get; set; }
        public string UpdateIP { get; set; }
        public DateTime UpdateDate { get; set; }
    }
}
