//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHtlReg_DTL_P1_10
    {
        public int HotelID { get; set; }
        public string HotelName { get; set; }
        public string HotelDisplayName { get; set; }
        public string LandMark { get; set; }
        public string HotelAddress1 { get; set; }
        public string HotelAddress2 { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public int PinCode { get; set; }
        public string State { get; set; }
        public Nullable<bool> Plan1 { get; set; }
        public Nullable<byte> Plan1Rooms { get; set; }
        public Nullable<int> PriceO10Hr { get; set; }
        public Nullable<int> PriceS10Hr { get; set; }
        public string CheckInTime { get; set; }
        public Nullable<bool> ForUnMarriedLocal { get; set; }
        public Nullable<byte> Star { get; set; }
        public bool IsAcive { get; set; }
        public int CreateBy { get; set; }
        public string CreateIP { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public string UpdateIP { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<byte> CommandID { get; set; }
    }
}
